version: "3"

services:
  node:
    image: 387125961759.dkr.ecr.ap-northeast-1.amazonaws.com/jihyo-note-ecr:dev-web-67bdcdf50035d7f72e72886d47f6a8842148ab9b
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    ports:
      - "3000:80"
    logging:
      driver: awslogs
      options:
        awslogs-create-group: "true"
        awslogs-group: /aws/ecs/jihyo-note/web/${ENVIRONMENT}/node
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: jihyo-note-web-node
