version: "3"

services:
  node:
    image: ${NODE_IMAGE}
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    ports:
      - "3000:3000"
    logging:
      driver: awslogs
      options:
        awslogs-create-group: "true"
        awslogs-group: /aws/ecs/jihyo-note/web/${ENVIRONMENT}/node
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: jihyo-note-web-node
