version: 1
task_definition:
  ecs_network_mode: awsvpc
  task_execution_role: arn:aws:iam::387125961759:role/ecsTaskExecutionRole
  ContainerPort: 3000
  HostPort: 80
  Protocol: tcp
  task_size:    
    cpu_limit: 1024
    mem_limit: 1024
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - subnet-26e41f0d
      security_groups:
        - sg-1ff48261
