version: 1
task_definition:  
  task_execution_role: arn:aws:iam::387125961759:role/ecsTaskExecutionRole
  ContainerPort: 3000
  HostPort: 80
  Protocol: tcp
  task_size:    
    cpu_limit: 512
    mem_limit: 1024