name: CI
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - name: Build
        run: |
          yarn install --frozen-lockfile --ignore-scripts --prefer-offline
          yarn build
