name: Deploy to Dev
concurrency: dev
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions: write-all
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: chrnorm/deployment-action@releases/v1
        name: Create Deployment
        id: deployment
        with:
          token: ${{ secrets.HUB_TOKEN }}
          ref: ${{ github.sha }}
          initial_status: in_progress
          target_url: http://dev.dioong.com
          environment: dev
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Web
        env:
          ENVIRONMENT: dev
        run: |
          yarn install --frozen-lockfile --ignore-scripts --prefer-offline
          yarn build
      - name: Build and push Web
        id: web_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/jihyo-note:dev-web-${{ github.sha }}
      - name: Image digest
        run: |
          echo web image: ${{ steps.web_build.outputs.digest }}
      - uses: marocchino/setup-ecs-cli@v1
        with:
          version: v1.21.0
      